name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u mwalczykpl --password-stdin
      - name: Deploy Image
        run: bash scripts/build-push.sh
        env:
          NAME: latest
